name: zynq-ebaz4205-use-precompiled-uboot

on:
  workflow_dispatch:
  
env:
  CONFIG_FILE: zynq-zed-lite.config
  DEVICE_NAME: zynq-ebaz4205
  TARGET_NAME: zynq
  SSH_ACTIONS:  true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: 初始化环境
      run: |
          sudo apt update
          sudo apt install build-essential ccache ecj fastjar file g++ gawk \
          gettext git java-propose-classpath libelf-dev libncurses5-dev \
          libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
          python3-distutils python3-setuptools rsync subversion swig time \
          xsltproc zlib1g-dev
          
    - name: Checkout OpenWrt repository
      uses: actions/checkout@v2
      with:
        repository: 'openwrt/openwrt'

    - name: 获取内核版本
      shell: bash {0}
      run: |
        KERNEL_VERSION=$(cat target/linux/${{ env.TARGET_NAME }}/Makefile | grep KERNEL_PATCHVER | sed -r 's|.*([0-9]+.[0-9]+)$|\1|')
        LINUX_VERSION=$(cat include/kernel-$KERNEL_VERSION | grep LINUX_VERSION-$KERNEL_VERSION | sed -r 's|.*(\.[0-9]+)$|\1|')
        echo "KERNEL_VERSION=$KERNEL_VERSION$LINUX_VERSION" >> $GITHUB_ENV   
        echo "KERNEL_VERSION=$KERNEL_VERSION$LINUX_VERSION"

    - name: 导入第三方包，更新feed
      run: |
        #### add luci-app-ssr-plus #### 
        git clone --depth=1 https://github.com/fw876/helloworld.git package/helloworld
        svn checkout https://github.com/coolsnowwolf/lede/trunk/tools/ucl tools/ucl
        svn checkout https://github.com/coolsnowwolf/lede/trunk/tools/upx tools/upx
        for i in "dns2socks" "microsocks" "ipt2socks" "pdnsd-alt" "redsocks2"; do 
        svn checkout "https://github.com/immortalwrt/packages/trunk/net/$i" "package/helloworld/$i"; 
        done
        sed -i '23a\tools-y += ucl upx' tools/Makefile # 使用sed插入特定行，在未来可能会出现问题
        sed -i '41a\$(curdir)/upx/compile := $(curdir)/ucl/compile' tools/Makefile
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
#    - name: SSH连接，手动 make menuconfig
#      uses: sypopo/debugger-action@master
#      if: env.SSH_ACTIONS == 'true'
    
    - name: 配置config
      run: | 
        git clone https://github.com/Elrori/openwrt-auto.git
        cp openwrt-auto/config/$CONFIG_FILE .config
        
    - name: 下载软件包
      id: package
      run: |
        make defconfig
        make download -j$(nproc)

    - name: 固件编译
      id: compile
      run: |
        make -j$(nproc) V=sc

    - name: 制作镜像
      run: |
        echo "重新编译"
        mkdir artifacts
        svn checkout https://github.com/Elrori/EBAZ4205/trunk/archive/2018.3-1 artifacts/fpga
        cp artifacts/fpga/zynq-ebaz4205.dts build_dir/target-*/linux-zynq/linux-${{ env.KERNEL_VERSION }}/arch/arm/boot/dts/zynq-zed.dts
        make -j$(nproc) V=sc
        cp build_dir/target-*/linux-zynq/linux-${{ env.KERNEL_VERSION }}/arch/arm/boot/dts/zynq-zed.dtb build_dir/target-*/linux-zynq/linux-${{ env.KERNEL_VERSION }}/arch/arm/boot/dts/zynq-ebaz4205.dtb
        
        echo "重新编译成功，开始制作ebaz4205镜像"
        echo -e "bootargs=console=ttyPS0,115200n8 root=/dev/mmcblk0p2 rootwait earlyprintk \n\
        uenvcmd=run sdbootfit \n\
        sdbootfit=echo Run uEnv.txt copying Linux from SD to RAM... && \n\
        fatload mmc 0 0x1000000 fit.itb && \n\
        echo Boot fit.itb from RAM && \n\
        bootm 0x1000000;" > artifacts/uEnv.txt
        cp build_dir/target-*/linux-zynq/Image artifacts/
        cp build_dir/target-*/linux-zynq/linux-${{ env.KERNEL_VERSION }}/arch/arm/boot/dts/zynq-ebaz4205.dtb artifacts/
        cp build_dir/target-*/linux-zynq/root.ext4 artifacts/
        gzip -f -9n -c artifacts/Image > artifacts/Image.gz
        scripts/mkits.sh -D ebang_zynq-ebaz4205 -o $(pwd)/artifacts/fit.its -k $(pwd)/artifacts/Image.gz -C gzip   -d $(pwd)/artifacts/zynq-ebaz4205.dtb   -a 0x8000 -e 0x8000    -c "config-1" -A arm -v 5.10.107
        staging_dir/host/bin/mkimage -f $(pwd)/artifacts/fit.its $(pwd)/artifacts/fit.itb
        staging_dir/host/bin/mkfs.fat $(pwd)/artifacts/boot -C 16384
        staging_dir/host/bin/mcopy -i $(pwd)/artifacts/boot $(pwd)/artifacts/fpga/BOOT.bin ::boot.bin
        staging_dir/host/bin/mcopy -i $(pwd)/artifacts/boot $(pwd)/artifacts/uEnv.txt ::uEnv.txt
        staging_dir/host/bin/mcopy -i $(pwd)/artifacts/boot $(pwd)/artifacts/fit.itb ::fit.itb
        export PATH=$PATH:staging_dir/host/bin
        target/linux/zynq/image/gen_zynq_sdcard_img.sh $(pwd)/artifacts/openwrt-zynq-ebang_zynq-ebaz4205-ext4-sdcard-precompileduboot.img.gz $(pwd)/artifacts/boot $(pwd)/artifacts/root.ext4 16 512
        gzip -f -9n -c artifacts/openwrt-zynq-ebang_zynq-ebaz4205-ext4-sdcard-precompileduboot.img.gz > artifacts/openwrt-zynq-ebang_zynq-ebaz4205-ext4-sdcard-precompileduboot.img.gz.new
        rm -rf artifacts/openwrt-zynq-ebang_zynq-ebaz4205-ext4-sdcard-precompileduboot.img.gz
        mv artifacts/openwrt-zynq-ebang_zynq-ebaz4205-ext4-sdcard-precompileduboot.img.gz.new artifacts/openwrt-zynq-ebang_zynq-ebaz4205-ext4-sdcard-precompileduboot.img.gz
        rm -rf artifacts/Image artifacts/boot artifacts/fit.its artifacts/fpga artifacts/root.ext4

    - name: 计算sha256,准备打包
      if: env.LATEST_VERSION == 0
      shell: bash {0}
      run: |
        for file in artifacts/*.gz; do
          sudo bash -c "sha512sum $file | sed -r 's|([0-9a-z]+).*|\1|g' > $file.sha512sum"
          sudo mv $file* artifacts/
        done

    - name: 创建 release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.KERNEL_VERSION }}-${{ env.DEVICE_NAME }}-precompileduboot
        release_name: Release v${{ env.KERNEL_VERSION }}-${{ env.DEVICE_NAME }}-precompileduboot
        draft: false
        prerelease: false
        
    - name: 上传 release
      uses: NBTX/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        targets: artifacts/*
