name: zynq

on:
  workflow_dispatch:
  
env:
  CONFIG_FILE: zynq-zed-lite.config
  DEVICE_NAME: zynq-zed
  TARGET_NAME: zynq
  SSH_ACTIONS:  true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    
    - name: Checkout OpenWrt repository
      uses: actions/checkout@v2
      with:
        repository: 'openwrt/openwrt'
        
    - name: Get Kernel version
      shell: bash {0}
      run: |
        KERNEL_VERSION=$(cat target/linux/${{ env.TARGET_NAME }}/Makefile | grep KERNEL_PATCHVER | sed -r 's|.*([0-9]+.[0-9]+)$|\1|')
        LINUX_VERSION=$(cat include/kernel-$KERNEL_VERSION | grep LINUX_VERSION-$KERNEL_VERSION | sed -r 's|.*(\.[0-9]+)$|\1|')
        echo "KERNEL_VERSION=$KERNEL_VERSION$LINUX_VERSION" >> $GITHUB_ENV
          
    - name: 初始环境
      run: |
          sudo apt update
          sudo apt install build-essential ccache ecj fastjar file g++ gawk \
          gettext git java-propose-classpath libelf-dev libncurses5-dev \
          libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
          python3-distutils python3-setuptools rsync subversion swig time \
          xsltproc zlib1g-dev

    - name: 导入第三方包，更新feed
      run: |
        #### add luci-app-ssr-plus #### 
        git clone --depth=1 https://github.com/fw876/helloworld.git package/helloworld
        svn checkout https://github.com/coolsnowwolf/lede/trunk/tools/ucl tools/ucl
        svn checkout https://github.com/coolsnowwolf/lede/trunk/tools/upx tools/upx
        for i in "dns2socks" "microsocks" "ipt2socks" "pdnsd-alt" "redsocks2"; do 
        svn checkout "https://github.com/immortalwrt/packages/trunk/net/$i" "package/helloworld/$i"; 
        done
        # 使用sed插入特定行，在未来可能会出现问题
        sed -i '23a\tools-y += ucl upx' tools/Makefile
        sed -i '41a\$(curdir)/upx/compile := $(curdir)/ucl/compile' tools/Makefile
        
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    #- name: SSH连接，手动 make menuconfig
    #  uses: sypopo/debugger-action@master
    #  if: env.SSH_ACTIONS == 'true'
    
    - name: 配置config
      run: |
        git clone https://github.com/Elrori/openwrt-auto.git 
        cp openwrt-auto/config/$CONFIG_FILE .config
        
    - name: 下载软件包
      id: package
      run: |
        make defconfig
        make download -j$(nproc)

    - name: 固件编译
      id: compile
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) V=sc

    - name: 准备打包
      if: env.LATEST_VERSION == 0
      shell: bash {0}
      run: |
        mkdir artifacts
        for file in bin/targets/*/*/*.gz; do
          sudo bash -c "sha512sum $file | sed -r 's|([0-9a-z]+).*|\1|g' > $file.sha512sum"
          sudo mv $file* artifacts/
        done

    - name: 创建 release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.KERNEL_VERSION }}-${{ env.DEVICE_NAME }}
        release_name: Release v${{ env.KERNEL_VERSION }}-${{ env.DEVICE_NAME }}
        draft: false
        prerelease: false
        
    - name: 上传 release
      uses: NBTX/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        targets: artifacts/*
